---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: mockserver
description: Mockserver for development and test
serialPipeline:
  stages:
  - targetId: development
  - targetId: test
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: development
description: Development Environment
gke:
  cluster: projects/$PROJECT_ID/locations/southamerica-east1/clusters/development
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: test
description: Test Environment
gke:
  cluster: projects/$PROJECT_ID/locations/southamerica-east1/clusters/test