apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver
spec:
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
      - name: mockserver
        image: gcr.io/rengue/mockserver:latest
        ports:
          - containerPort: 1080